/*
 * Automatically generated by premake5.
 * Do not touch!
 */

#ifdef GIT_DESCRIBE
#	undef GIT_DESCRIBE
#endif
#ifdef GIT_DIRTY
#	undef GIT_DIRTY
#endif
#ifdef GIT_HASH
#	undef GIT_HASH
#endif
#ifdef GIT_TAG
#	undef GIT_TAG
#endif
#ifdef GIT_BRANCH
#	undef GIT_BRANCH
#endif
#ifdef PRJ_TIMESTAMP
#	undef PRJ_TIMESTAMP
#endif

#define GIT_DESCRIBE "31e204f-dirty"
#define GIT_DIRTY 1
#define GIT_HASH "31e204f10b8d4378478bc2ce000700ab70b3042a"
#define GIT_TAG ""
#define GIT_BRANCH "develop"
#define PRJ_TIMESTAMP "Fri Dec 13 18:45:56 2024"
