/*
 * Automatically generated by premake5.
 * Do not touch!
 */

#ifdef GIT_DESCRIBE
#	undef GIT_DESCRIBE
#endif
#ifdef GIT_DIRTY
#	undef GIT_DIRTY
#endif
#ifdef GIT_HASH
#	undef GIT_HASH
#endif
#ifdef GIT_TAG
#	undef GIT_TAG
#endif
#ifdef GIT_BRANCH
#	undef GIT_BRANCH
#endif
#ifdef PRJ_TIMESTAMP
#	undef PRJ_TIMESTAMP
#endif

#define GIT_DESCRIBE "0ca0ba8-dirty"
#define GIT_DIRTY 1
#define GIT_HASH "0ca0ba8b4003b91e6d0e12765295444f1d108919"
#define GIT_TAG ""
#define GIT_BRANCH "develop"
#define PRJ_TIMESTAMP "Sun Dec 01 13:27:42 2024"
