/*
 * Automatically generated by premake5.
 * Do not touch!
 */

#ifdef GIT_DESCRIBE
#	undef GIT_DESCRIBE
#endif
#ifdef GIT_DIRTY
#	undef GIT_DIRTY
#endif
#ifdef GIT_HASH
#	undef GIT_HASH
#endif
#ifdef GIT_TAG
#	undef GIT_TAG
#endif
#ifdef GIT_BRANCH
#	undef GIT_BRANCH
#endif
#ifdef PRJ_TIMESTAMP
#	undef PRJ_TIMESTAMP
#endif

#define GIT_DESCRIBE "f515f7d-dirty"
#define GIT_DIRTY 1
#define GIT_HASH "f515f7d459a4cdd60ccad558704bfc8f02645572"
#define GIT_TAG ""
#define GIT_BRANCH "develop"
#define PRJ_TIMESTAMP "Thu Dec 05 21:05:59 2024"
